#!/bin/bash

# Install Flutter
git clone https://github.com/flutter/flutter.git -b stable --depth 1
export PATH="$PATH:$(pwd)/flutter/bin"

# Build
flutter pub get
flutter build web --release --web-renderer canvaskit

# Post-build
cp -r build/web public/
